@startuml
'https://plantuml.com/sequence-diagram

autonumber

messenger -> roomService : createNewRoomInvitation (Grpc)
roomService -> accountService : exist (Grpc)
roomService -> messenger
messenger -> messenger: wait for user confirmation

@enduml